# Link for the iCal file for your company's google calendar
calendar_ics_link: ""
# Private link for your company's google calendar, used to link directly to the calendar without having to log in
calendar_link: ""
