# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 45) do

  create_table "attachments", :force => true do |t|
    t.string   "attachable_type"
    t.integer  "attachable_id"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "candidates", :force => true do |t|
    t.string   "last_name"
    t.string   "first_name"
    t.text     "notes"
    t.string   "position"
    t.string   "website"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "status"
    t.string   "phone_number"
    t.string   "email"
    t.string   "resume_file_name"
    t.string   "resume_content_type"
    t.integer  "resume_file_size"
  end

  create_table "comments", :force => true do |t|
    t.integer  "commenter_id"
    t.text     "content"
    t.integer  "commentable_id"
    t.string   "commentable_type"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "doctors", :force => true do |t|
    t.string  "name"
    t.boolean "in_network"
    t.string  "address"
    t.integer "copay"
    t.text    "comments"
    t.string  "specialty"
    t.string  "phone_number"
    t.string  "type"
  end

  create_table "homeworks", :force => true do |t|
    t.integer  "homework_id"
    t.integer  "answer_id"
    t.integer  "solution_id"
    t.datetime "completed_at"
    t.datetime "provided_at"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "interviewings", :force => true do |t|
    t.integer  "interview_id"
    t.integer  "user_id"
    t.datetime "start_time"
    t.datetime "end_time"
    t.text     "topics"
    t.text     "notes"
    t.string   "verdict"
    t.string   "verdict_explanation"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "interviews", :force => true do |t|
    t.datetime "scheduled_at"
    t.text     "notes"
    t.integer  "candidate_id"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "marks", :force => true do |t|
    t.integer "user_id"
    t.integer "photo_id"
    t.float   "x_coord"
    t.float   "y_coord"
  end

  create_table "photos", :force => true do |t|
    t.integer  "user_id"
    t.datetime "created_at"
    t.datetime "taken_at"
    t.text     "description"
    t.string   "name"
    t.string   "mimetype"
  end

  create_table "portraits", :force => true do |t|
    t.integer "parent_id"
    t.string  "content_type"
    t.string  "filename"
    t.integer "size"
    t.integer "width"
    t.integer "height"
    t.string  "thumbnail"
  end

  create_table "positions", :force => true do |t|
    t.string  "title"
    t.text    "description"
    t.integer "team_id"
    t.integer "user_id"
  end

  create_table "screens", :force => true do |t|
    t.integer  "screener_id"
    t.datetime "scheduled_at"
    t.integer  "candidate_id"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.text     "notes"
  end

  create_table "sessions", :force => true do |t|
    t.string   "session_id"
    t.text     "data"
    t.datetime "updated_at"
  end

  add_index "sessions", ["session_id"], :name => "index_sessions_on_session_id"
  add_index "sessions", ["updated_at"], :name => "index_sessions_on_updated_at"

  create_table "taggings", :force => true do |t|
    t.integer "tag_id"
    t.integer "user_id"
    t.integer "tagger_id"
  end

  create_table "teams", :force => true do |t|
    t.string "name"
    t.text   "description"
    t.string "logo_url"
  end

  create_table "users", :force => true do |t|
    t.string   "login"
    t.string   "email"
    t.string   "crypted_password",          :limit => 40
    t.string   "salt",                      :limit => 40
    t.datetime "created_at"
    t.datetime "updated_at"
    t.text     "bio"
    t.integer  "portrait_id"
    t.string   "portrait_url"
    t.string   "portrait_thumbnail_url"
    t.string   "remember_token"
    t.datetime "remember_token_expires_at"
    t.string   "activation_code",           :limit => 40
    t.datetime "activated_at"
    t.string   "password_reset_code",       :limit => 40
    t.integer  "admin"
    t.date     "birthday"
    t.string   "cell"
    t.string   "extension"
    t.string   "aim"
    t.string   "yahoo"
    t.string   "msn"
    t.boolean  "former",                                  :default => false
  end

end
